apiVersion: v1
kind: Service
metadata: 
  name: argocd-svc
  labels:
    name: argocd-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    app: argocd-listener
