apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: argocd-listener-fin
  namespace: default
spec:
  serviceAccountName: docker-login
  triggers:
    - name: autre-trigger
      interceptors:
        - ref:
            name: "cel"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev/v1alpha1
          params:
            - name: "filter"
              value: >
                body["branch"] == 'dev' && body["author"] == 'aychakarma'
      bindings:
        - ref: clone-trigger
      template:
        ref: clone-templates
  resources:
    kubernetesResource:
      serviceType: NodePort
