apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-pushs
spec:
  workspaces:
  - name: k8s
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  params:
  - name: image
    description: Reference of the image to be pushed.
  steps:
  - name: docker-login
    image: docker.io/library/docker:stable
    env:
    - name: DOCKER_HOST
      value: unix:///var/run/docker.sock
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    securityContext:
      runAsUser: 0
    workingDir: /workspace/k8s
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    script: |
      echo "aychakarma12345678910" | docker login -u "karma12" --password-stdin
      docker push $(params.image)
