apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nexus-task
spec:
  workspaces:
  - name: k8s
  steps:
  - name: maven-builds
    image: maven:3.6.3-openjdk-11
    workingDir: /workspace/k8s
    script: |
      mvn deploy
