apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: complete-pipelines
spec:
  description: "This pipeline clones a git repo, makes mvnw executable, and builds with Maven, then builds and pushes a Docker image."
  params:
    - name: repo-url
      type: string
      description: "The git repo URL to clone from."
    - name: branch
      type: string
      description: "The git branch to clone."
    - name: image
      type: string
      description: "The Docker image reference."
    - name: context
      type: string
      description: "The Docker build context path."
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"

    - name: maven-build
      taskRef:
        name: maven-task
      runAfter:
        - fetch-source
      workspaces:
        - name: shared-data
      params:
        - name: maven-command
          value: "clean install -DskipTests"

    - name: docker-build
      taskRef:
        name: docker-build
      runAfter:
        - maven-build
      workspaces:
        - name: shared-data
      params:
        - name: image
          value: "$(params.image)"
        - name: context
          value: "$(params.context)"

    - name: docker-push  # Ajout de la tâche pour pousser l'image Docker
      taskRef:
        name: docker-push
      runAfter:
        - docker-build
      workspaces:
        - name: shared-data
      params:
        - name: image
          value: "$(params.image)"
          
    - name: prepare-deployment
      taskRef:
        name: prepare-deployment
      runAfter:
        - docker-push
      workspaces:
        - name: shared-data
