apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: clone-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: argocd-
      spec:
        pipelineRef:
          name: clone-reads
        workspaces:
          - name: k8s
            persistentVolumeClaim:
              claimName: tt
        params:
          - name: repo-url
            value: "https://github.com/aychakarma/fin-k8s-pppfe.git"
          - name: branch
            value: "dev"
          - name: image
            value: "karma12/eqdev-spring-boot:f11"
          - name: context
            value: "/workspace/k8s"
        serviceAccountName: docker-login

