apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: clone-templates
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: argocd-
        annotations:
          argocd.argoproj.io/compare-options: Skip  # Annotation ajoutée
      spec:
        pipelineRef:
          name: argocd-final
        workspaces:
          - name: k8s
            persistentVolumeClaim:
              claimName: tt
        params:
          - name: repo-url
            value: "https://github.com/aychakarma/fin-k8s-pppfe.git"
          - name: branch
            value: "dev"
          - name: image
            value: "karma12/eqdev-spring-boot:f14"
          - name: context
            value: "/workspace/k8s"
          - name: sonar_login
            value: "admin"  
          - name: sonar_password
            value: "aycha"
          - name: nexus_login
            value: "admin"
          - name: nexus_password
            value: "nexus"
          - name: nexus_url
            value: "http://192.168.192.4:8081" 
        serviceAccountName: docker-login
        timeout: 2h30m0s 
