apiVersion: v1
kind: Service
metadata:
  name: eqtest-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 30005
  selector:
    app: backend-app
