apiVersion: v1
kind: Service
metadata:
  name: nouveau-backend-service
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: backend-app
