apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-test
  labels:
    name: backend-service-test
spec:
  type: NodePort
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 30007
  selector:
    app: backend-app-test
