apiVersion: v1
kind: Service
metadata: 
  name: springboot-crud-svc
  labels:
    name: springboot-k8s-mysql
spec:
  type: NodePort
  ports:
    - port: 8020  # Change to a different port, e.g., 8021
      targetPort: 8020
      nodePort: 30009  # Change to a different node port, e.g., 30007
  selector:
    app: springboot-k8s-mysql
