apiVersion: v1
kind: Service
metadata: 
  name: springboot-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 30007
  selector:
    app: backend-app
