apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-test
  labels:
    app: backend-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app-test
  template:
    metadata:
      labels:
        app: backend-app-test
    spec:
      containers:
        - name: backend-container
          image: karma12/crud2-spring-boot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8030
          env:
            - name: DB_HOST
              value: mysqldb-test
            - name: DB_NAME
              value: crud-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Password123
