apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddev-deploy
  labels:
    app: backend-app
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-db-cred: "database/roles/mysqlrole"
    vault.hashicorp.com/role: "web"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: karma12/eqdev-spring-boot:d11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8020
