apiVersion: v1
kind: Service
metadata: 
  name: dev-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8040
      targetPort: 8040
      nodePort: 30008
  selector:
    app: backend-app