apiVersion: v1
kind: Service
metadata: 
  name: springboot-test
  labels:
    name: test-service
spec:
  type: NodePort
  ports:
    - port: 8020
      targetPort: 8020
      nodePort: 30007  # Choisir un nouveau nodePort
  selector:
    app: test-app  # Changer le nom de l'application
