apiVersion: v1
kind: Service
metadata: 
  name: devss-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8060
      targetPort: 8060
      nodePort: 30005
  selector:
    app: backend-app
