apiVersion: apps/v1
kind: Deployment
metadata:
  name: eqprod-deploy
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: karma12/prod-spring-boot:fin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8030
          env:
            - name: DB_HOST
              value: eqproddb
            - name: DB_NAME
              value: crud-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Password123
