apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
  labels:
   app: springboot-k8s-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
      - name: springboot-k8s-mysql
        image: karma12/eqdev-spring-boot:fb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020  # Change to a different port, e.g., 8021
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: devops
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: Password123
