apiVersion: v1
kind: Service
metadata: 
  name: mysqltest-db
  labels:
    name: mysql-service
spec:
  ports:
    - port: 3308  # Change to a different port, e.g., 3307
      targetPort: 3306
  selector:
    app: mysqldb
