apiVersion: v1
kind: Service
metadata: 
  name: mysql
  labels:
    name: mysql
spec:
  ports:
    - port: 3309 # Change to a different port, e.g., 3307
      targetPort: 3306
  selector:
    app: mysql
