apiVersion: apps/v1
kind: Deployment
metadata:
  name: eqtest-mysql-deploy
  labels:
    app: eqtestdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eqtestdb
  template:
    metadata:
      labels:
        app: eqtestdb
    spec:
      containers:
        - name: eqtestdb
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password123
            - name: MYSQL_DATABASE
              value: crud-db
